### ISSUE TITLE
Visul panel

### ISSUE THREAD

**Issue by mmojadad** [aldabil21/opencart-webpush-pwa#3]
Hi
Do you have plan to  create  a special view page in admin panel to make it easier for non-coders to control the push events visually? When?

Regards

**Comment by aldabil21** [comment]
Hi @mmojadad 

As you also mentioned here #2 
This definitely will be a nice improvment, also the code should be written and packed as `.ocmod` extension plugin to be uploaded in the extensions interface easily by non-coders.
Although with this base setup, it will not be really hard to implement, you already have the controller and model been setup, all you have to do is add your query functions, plus a simple interface page in the admin panel. 

My client did not continue his project though, otherwise I might be doing it. Perhaps if I could spare some free time in future I would improve it.

If you have such a use case/need for a custom push notification plugin for your project or a client of your's, DM me at twitter @aldabil21, cuz to be honest, I might need some support/sponser to work on it.
 
Regards

**Comment by mmojadad** [comment]
@aldabil21
Yes, Sure. I will be in contact

**Comment by mmojadad** [comment]
> 
> 
> Hi @mmojadad
> 
> As you also mentioned here #2
> This definitely will be a nice improvment, also the code should be written and packed as `.ocmod` extension plugin to be uploaded in the extensions interface easily by non-coders.
> Although with this base setup, it will not be really hard to implement, you already have the controller and model been setup, all you have to do is add your query functions, plus a simple interface page in the admin panel.
> 
> My client did not continue his project though, otherwise I might be doing it. Perhaps if I could spare some free time in future I would improve it.
> 
> If you have such a use case/need for a custom push notification plugin for your project or a client of your's, DM me at twitter @aldabil21, cuz to be honest, I might need some support/sponser to work on it.
> 
> Regards

Hi
Do you using Telegram app? Its more than easy for me to be connect with you via Telegram.

**Comment by aldabil21** [comment]
@mmojadad I'm sorry I don't use it, but you can find all my contacts listed here  https://aldabil.me
